[package]
name = "lz4"
license = "MIT"
version = "1.5.128"
authors = [ "Artem V. Navrotskiy <bozaro@buzzsoft.ru>" ]
build = "src/build.rs"
description = "Rust LZ4 bindins library."
repository = "https://github.com/bozaro/lz4-rs"

[[bin]]
name = "lz4"
test = false

[dependencies]
libc = "*"

[build-dependencies]
gcc = "*"
