[package]
name = "lz4"
license = "MIT"
version = "1.19.131"
authors = [ "Artem V. Navrotskiy <bozaro@buzzsoft.ru>" ]
build = "src/build.rs"
description = "Rust LZ4 bindings library."
repository = "https://github.com/bozaro/lz4-rs"
documentation = "https://bozaro.github.io/lz4-rs/lz4/"

[[bin]]
name = "lz4"
test = false
doc = false

[dependencies]
libc = "0.2.16"

[dev-dependencies]
rand = "0.3.14"
skeptic = "0.6.1"

[build-dependencies]
gcc = "0.3.35"
skeptic = "0.6.1"
