name: Test

on:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_INCREMENTAL: 0

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.43.0
          override: true
          components: rustfmt
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Check Rust formatting
        run: cargo fmt -- --check
      - name: build
        run: cargo build --release
      - name: unit tests
        run: cargo test -- --nocapture
